# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb1ec2e435ec143a5097fc3034ddf37db95e89a4e04e9a6bccea7546e7d4e5ab34b7377aad2c961b1d64863e4f4125c9f31bc9c270f655a7d6f298ec5e873142

test:
  secret_key_base: a71875ef4454aa62c044fb4a74faf7bbc13fc608fde77e621c3064f97bf2906f446c747ba761bba5cb7ccee9ff2c0ae2a41d0be6ef23a0c1f19ebabd909428cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
